### ISSUE TITLE
Yarn not updating to the latest

### ISSUE THREAD

**Issue by joshuatcasey** [paketo-buildpacks/yarn#234]
This buildpack should have the latest two versions of Yarn: 1.22.18 and 1.22.19 (https://github.com/yarnpkg/yarn/releases, current as of 2022-06-19).

Context about why is (on slack)[https://paketobuildpacks.slack.com/archives/CUD6R3CPL/p1655491000633989] but I'll make an issue here for visibility.

Note: Over on https://github.com/joshuatcasey/yarn/actions/runs/2526304387 I have a workflow that basically updates Yarn. I think the only step lacking is uploading the tarballs somewhere. Another approach: use the tarballs from github/yarnpkg/yarn and perform the "compilation" during the build process.

**Comment by ryanmoran** [comment]
This appears to have been an issue with dep-server. Additionally, we will be rewriting all of our dependency management code. @joshuatcasey do we still think this issue needs to be addressed?

**Comment by joshuatcasey** [comment]
@ryanmoran I do not feel that this issue needs to be addressed separately than the overall dependency management code.

Closing.
