### ISSUE TITLE
Missing version in buildpack.toml

### ISSUE THREAD

**Issue by ThomasVitale** [paketo-buildpacks/yarn#359]
From what I can see, other Paketo Buildpacks come with a `version` property in the `buildpack.toml `file. Should this buildpack provides that, too? Right now it's missing.

```
[buildpack]
  ...
  version = "{{.version}}"
```

**Comment by ThomasVitale** [comment]
Thanks a lot for the detailed explanation @robdimsdale. Working mostly with Java-related buildpacks, I wasn't aware of the different approach, thanks for the pointers in the jam project. I had issues when trying to build an ARM64 version of the Paketo Builder using [these scripts](https://github.com/dashaun/paketo-arm64/blob/main/scripts/tiny.sh#L39) that expect a version to be defined in the `buildpack.toml` file.

**Comment by robdimsdale** [comment]
Ah, yeah, that makes sense. The community-supported ARM64 scripts were developed by folks who mostly work with the java buildpacks.

FYI official support for ARM64 for all paketo buildpacks is on the roadmap for 2023. I hope we can get started on that soon.

**Comment by dashaun** [comment]
That change seems to be causing my scripts to fail for the java/java-native-image buildpacks too.  I'm digging into this now.

**Comment by robdimsdale** [comment]
@dashaun I think what happened is the java buildpacks recently added support for front-end applications by including the node/yarn buildpacks in the build order. So the Java buildpacks now contain a mixture of buildpacks that have the `version = {{ .version }}` structure and ones that just have the field missing from the `buildpack.toml`.

**Comment by ThomasVitale** [comment]
@robdimsdale ah, got it, thank you! I couldn't figure out why the yarn and node-engine buildpacks were included in the tiny builder. I must have missed that change.

**Comment by dashaun** [comment]
Yes, thanks @robdimsdale for the tip! @ThomasVitale I'm working on the a fix now.

**Comment by dashaun** [comment]
> 

Just thinking out loud here.

Until now, all of the other `buildpacks` could be packaged like this
```
create-package --destination ./out --version "$VERSION"
pack buildpack package "gcr.io/$BUILDPACK:$VERSION"
```
The `yarn` buildpack needs something like this:
```
if $BUILDPACK == yarn
  # packages using `jam` creates buildpack.toml that has the version AND creates buildpack with `pack` 
  $WORK/$BUILDPACK/scripts/package.sh --version $VERSION
else
 # use the existing workflow
```

Does that look right-ish?

**Comment by robdimsdale** [comment]
@dashaun `scripts/package.sh --version $VERSION` will build the buildpack with the desired version, though I haven't tested it in the context of your tooling.

**Comment by dashaun** [comment]
It's working for me!

Now I'm using the `ARM64` version of `jam` (2.1.1)

I should make a PR for that update in this repo.....

**Comment by dashaun** [comment]
@ThomasVitale I've worked around this change, in my scripts.  I think this issue can be closed.

**Comment by ThomasVitale** [comment]
Thanks a lot, @dashaun. I'll close this issue
