### ISSUE TITLE
Yarn update dependency workflow failure

### ISSUE THREAD

**Issue by pacostas** [paketo-buildpacks/yarn#598]
## Expected Behavior

The Update Dependencies workflow is failing because when it tries to update the buildpack.toml with the latest yarn versions, the file with extension `.tar.gz.asc` is not available for download.

This issue will be resolved once a newer version of yarn is available with the `.tar.gz.asc` file included in the release assets, although we don't know how much time will it take till the next release.

## Current Behavior

Failing to find the file with `.tar.gz.asc` extension.

## Possible Solution

1. Open PR to update the buildpack.toml file manually, that way it will not go through the update process
2. Skip this version by opening a PR which will exclude it from the newer versions

**Comment by sophiewigmore** [comment]
The latest yarn version,  we should just manually update I think! I'm not a Node maintainer though

**Comment by pacostas** [comment]
I see you have merged it https://github.com/paketo-buildpacks/yarn/pull/617 so no further action is needed :)

**Comment by pacostas** [comment]
Im closing this issue as there is not failure any more and the workaround is to update the dependencies manually.

**Comment by pacostas** [comment]
Im closing this issue as currently there is no failure and the workaround is to update the dependencies manually.
