### ISSUE TITLE
failed to fetch dependency: unexpected status code 404 while fetching "https://deps.paketo.io/yarn/yarn_1.22.19_linux_noarch_bionic_3235ba55.tgz"

### ISSUE THREAD

**Issue by felipe-vicente** [paketo-buildpacks/yarn#616]
```
Paketo Buildpack for Yarn 1.3.5
  Executing build process
    Installing Yarn
failed to fetch dependency: unexpected status code 404 while fetching "https://deps.paketo.io/yarn/yarn_1.22.19_linux_noarch_bionic_3235ba55.tgz"
ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 51
```

## Expected Behavior
```
Paketo Buildpack for Yarn 1.3.5
  Executing build process
    Installing Yarn
      Completed in 117ms
```

## Current Behavior
Cant download `https://deps.paketo.io/yarn/yarn_1.22.19_linux_noarch_bionic_3235ba55.tgz`

## Possible Solution
Turn the package available again

## Steps to Reproduce
Navigate to `https://deps.paketo.io/yarn/yarn_1.22.19_linux_noarch_bionic_3235ba55.tgz` on the browser

## Motivations
Cant deploy applications due to this problem

**Comment by sebastianplawner** [comment]
I'm having the same error today with Yarn 1.3.7 as well.

```[builder] Paketo Buildpack for Yarn 1.3.7
[builder]   Executing build process
[builder]     Installing Yarn
[builder] failed to fetch dependency: unexpected status code 404 while fetching "https://deps.paketo.io/yarn/yarn_1.22.19_linux_noarch_bionic_3235ba55.tgz"
[builder] ERROR: failed to build: exit status 1
```

**Comment by lortza** [comment]
Same here. This started happening today for Yarn 1.3.9.

```
[builder] Paketo Buildpack for Yarn 1.3.9
[builder]   Executing build process
[builder]     Installing Yarn
[builder] failed to fetch dependency: unexpected status code 404 while fetching "https://deps.paketo.io/yarn/yarn_1.22.19_linux_noarch_bionic_3235ba55.tgz"
```

**Comment by hwasurr** [comment]
```
Paketo Buildpack for Yarn 1.1.9
  Executing build process
    Installing Yarn
failed to fetch dependency: unexpected status code 404 while fetching "https://deps.paketo.io/yarn/yarn_1.22.19_linux_noarch_bionic_3235ba55.tgz"
```

**Comment by a1flecke** [comment]
we are also experiencing this

**Comment by CS10-85** [comment]
We have the same issue.

Paketo Buildpack for Yarn 1.3.5  
Executing build process  
Installing Yarn  
failed to fetch dependency: unexpected status code 404 while fetching https://deps.paketo.io/yarn/yarn_1.22.19_linux_noarch_bionic_3235ba55.tgz"  
failed to build: exit status 1

**Comment by felipe-vicente** [comment]
now it changed to 403

```
failed to fetch dependency: unexpected status code 403 while fetching "https://deps.paketo.io/yarn/yarn_1.22.19_linux_noarch_bionic_3235ba55.tgz"
```

**Comment by bntzio** [comment]
We are also experiencing this issue.

```
Paketo Buildpack for Yarn 1.3.5
  Executing build process
    Installing Yarn
failed to fetch dependency: unexpected status code 404 while fetching "https://deps.paketo.io/yarn/yarn_1.22.19_linux_noarch_bionic_3235ba55.tgz"
```

**Comment by zteric** [comment]
can someone please help on this? We are also experiencing this issue since yesterday...

**Comment by roliverio** [comment]
Please, we need the service to be restored. It seems that you deleted/changed/moved the S3 bucket with the installers/source code.

**Comment by hwasurr** [comment]
Older versions still seem to be having issues.

We have to use node version 14 for maintenance of legacy services, so the builder also has to use the previous version. So I still see an error message like this.

```
unexpected status code 404 while fetching "https://deps.paketo.io/yarn/yarn_1.22.19_linux_noarch_bionic_3235ba55.tgz
```

How can I solve this problem?
