### ISSUE TITLE
VPN - cert verification failed

### ISSUE THREAD

**Issue by novellat** [paketo-buildpacks/yarn#619]
When going through the company VPN, the yarn download from github fails
## Current Behavior
```
Paketo Buildpack for Yarn 1.3.10
  Executing build process
    Installing Yarn
failed to fetch dependency: failed to make request: Get "https://github.com/yarnpkg/yarn/releases/download/v1.22.22/yarn-v1.22.22.tar.gz": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

## Possible Solution
1. Add some switch to ignore certificate verification?
2. Let me know how can I circumvent it?
3. read .npmrc so that the correct artifactory is used? (probalby best solution)

## Steps to Reproduce
 I just ran this on my codebase:
```
 pack build example-no --buildpack paketo-buildpacks/nodejs \
  --builder paketobuildpacks/builder-jammy-base \
  --path examples/apps/nodejs/app

```

**Comment by mhdawson** [comment]
My guess is that the issue you are having is related to being behind a proxy.

I read that go (which is what the buildpacks are written in) support the environment variable `http_proxy`. Can you try and see if that resolvs the problem for you?

**Comment by mhdawson** [comment]
It's been over 3 weeks without a response from the OP. I'm going to close. Please let us know if that was not the right thing to do.
